### ISSUE TITLE
somehow enforce types in ClimateHealthTimeSeries class

### ISSUE THREAD

**Issue by KanduriC** [dhis2/chap-core#1]
not sure if I am allowed to go ahead and use pydantic, so did not make the decision

**Comment by sveinugu** [comment]
Omnipy includes pydantic (currently v1.10) as a requirement, so I would say to go ahead and use pydantic to enforce types, as I am in any case planning to use pydantic for the data wrangling/parsing. However, there is a performance overhead so it might not be needed if it is already used for creating/validating a csv file...
